import { StyleSheet, Platform } from 'react-native';

export const oldSchoolStyles = StyleSheet.create({
  headerImage: {
    opacity: 0.3,
    left: -30,
    top: -50,
  },
  titleContainer: {
    marginBottom: 16,
    alignItems: 'center',
  },
  oldSchoolTitle: {
    fontSize: 24,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#00FF00',
  },
  oldSchoolSubtitle: {
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginTop: 4,
    textAlign: 'center',
    color: '#00FF00',
  },
  oldSchoolDivider: {
    height: 2,
    backgroundColor: '#00FF00',
    width: '100%',
    marginVertical: 8,
  },
  oldSchoolContainer: {
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#00FF00',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  osHeader: {
    padding: 8,
    backgroundColor: '#000080',
    borderBottomWidth: 1,
    borderBottomColor: '#00FF00',
  },
  osMenuTitle: {
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: 'bold',
    color: '#00FF00',
  },
  osContentContainer: {
    padding: 8,
  },
  osDivider: {
    height: 1,
    backgroundColor: '#00FF00',
    width: '100%',
    marginVertical: 8,
  },
  osMonoText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 14,
    color: '#00FF00',
  },
  osStatsGrid: {
    padding: 8,
  },
  osStatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  osStatLabel: {
    flex: 3,
  },
  osStatValue: {
    flex: 1,
    alignItems: 'flex-end',
  },
  osSection: {
    marginTop: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#00FF00',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  osModalContainer: {
    flex: 1,
    padding: 16,
    marginTop: 40,
    backgroundColor: '#000000',
  },
  osModalTitle: {
    fontSize: 18,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: 'bold',
    color: '#00FF00',
  },
  osActionButton: {
    backgroundColor: 'rgba(0,255,0,0.1)',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 0,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#00FF00',
  },
  osLogoutButton: {
    backgroundColor: 'rgba(255,0,0,0.1)',
    borderColor: '#FF0000',
  },
  osUserCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 0,
    padding: 12,
    marginTop: 8,
    borderLeftWidth: 2,
    borderLeftColor: '#00FF00',
  },
  osUserInfo: {
    flex: 1,
  },
  osUserName: {
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#00FF00',
  },
  osUserActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  osIconButton: {
    marginLeft: 12,
  },
  osStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  osRoleBadge: {
    backgroundColor: 'rgba(0,255,0,0.1)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 0,
    alignSelf: 'flex-start',
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#00FF00',
  },
  osRoleBadgeText: {
    fontSize: 10,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: 'bold',
    color: '#00FF00',
  },
  osSkillsCard: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 0,
    padding: 12,
    marginTop: 8,
    borderLeftWidth: 2,
    borderLeftColor: '#00FF00',
  },
  osSkillsCardTitle: {
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#00FF00',
  },
  osSkillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  osSkillChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,255,0,0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 0,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#00FF00',
  },
  osAddSkillContainer: {
    marginVertical: 16,
    padding: 16,
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#00FF00',
  },
  osInput: {
    height: 40,
    borderWidth: 1,
    borderColor: '#00FF00',
    backgroundColor: 'rgba(0,0,0,0.7)',
    marginVertical: 16,
    padding: 8,
    color: '#00FF00',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  osButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  osButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#00FF00',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  osCancelButton: {
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  osAddButton: {
    backgroundColor: 'rgba(0,255,0,0.1)',
  },
  osButtonText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: '#00FF00',
  },
  osModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  osRoleModalContainer: {
    width: '80%',
    backgroundColor: '#000000',
    padding: 16,
    borderWidth: 1,
    borderColor: '#00FF00',
  },
});
